# Site settings
title: Notebook
email: noread@craigpaton.uk
description: > # this means to ignore newlines until "baseurl:"
  Programmers notebook
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notebook.craigpaton.uk"
asset_base_url: "http://notebook-assets.craigpaton.uk/notebook/"

# Google Analytics
# google_analytics_tracking_id: XX-XXXXXXXX-X

# Build settings
markdown: kramdown
highlighter: Rouge
timezone: Europe/London

collections: 
  synology:
    output: true
    nav_title: Synology
  testing:
    output: true
    nav_title: Testing
  meta:
    output: true
    nav_title: Meta
  git:
    output: true
    nav_title: Git
  raspberry-pi:
    output: true
    nav_title: Raspberry Pi
  web-development:
    output: true
    nav_title: Web Dev
  ops:
    output: true
    nav_title: Ops

exclude: 
- readme.txt

defaults:
-
  scope:
    path: ""
    type: "testing"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "synology"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "meta"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "git"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "raspberry-pi"
  values:
    layout: page
    page_display_sort_order: 100            
-
  scope:
    path: ""
    type: "web-development"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "ops"
  values:
    layout: page
    page_display_sort_order: 100                       