# Site settings
title: Notebook
email: noreply@craigpaton.uk
description: > # this means to ignore newlines until "baseurl:"
  Programmers notebook
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notebook.craigpaton.uk"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
# google_analytics_tracking_id: XX-XXXXXXXX-X

# Build settings
# markdown: rdiscount

highlighter: pygments
timezone: Europe/London

collections: 
- testing

exclude: 
- readme.txt