# Site settings
title: Notebook
email: noreply@craigpaton.uk
description: > # this means to ignore newlines until "baseurl:"
  Programmers notebook
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notebook.craigpaton.uk"
#twitter_username: jekyllrb
#github_username:  jekyll

# Google Analytics
# google_analytics_tracking_id: XX-XXXXXXXX-X

# Build settings
# markdown: rdiscount

highlighter: Rouge
timezone: Europe/London

collections: 
  test_collection:
    output: true
    nav_title: Test Collection
  testing:
    output: true
    nav_title: Testing
  synology:
    output: true
    nav_title: Synology

exclude: 
- readme.txt

defaults:
-
  scope:
    path: ""
    type: "testing"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "test_collection"
  values:
    page_display_sort_order: 100    
-
  scope:
    path: ""
    type: "synology"
  values:
    layout: page
    page_display_sort_order: 100