# Site settings
title: Notebook
email: noread@craigpaton.uk
description: > # this means to ignore newlines until "baseurl:"
  Programmers notebook
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notebook.craigpaton.uk"
asset_base_url: "http://notebook-assets.craigpaton.uk/notebook/"

# Google Analytics
# google_analytics_tracking_id: XX-XXXXXXXX-X

# Build settings
markdown: kramdown
highlighter: Rouge
timezone: Europe/London

collections: 
  synology:
    output: true
    nav_title: Synology
    display_order: 10
  testing:
    output: true
    nav_title: Testing
    display_order: 1
  meta:
    output: true
    nav_title: Meta
    display_order: 100
  git:
    output: true
    nav_title: Git
    display_order: 5
  raspberry-pi:
    output: true
    nav_title: Raspberry Pi
    display_order: 11
  web-development:
    output: true
    nav_title: Web Dev
    display_order: 3
  ops:
    output: true
    nav_title: Ops
    display_order: 12
  docker:
    output: true
    nav_title: Docker
    display_order: 6
  architecture:
    output: true
    nav_title: Architecture
    display_order: 2


exclude: 
- readme.txt

defaults:
-
  scope:
    path: ""
    type: "testing"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "synology"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "meta"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "git"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "raspberry-pi"
  values:
    layout: page
    page_display_sort_order: 100            
-
  scope:
    path: ""
    type: "web-development"
  values:
    layout: page
    page_display_sort_order: 100
-
  scope:
    path: ""
    type: "ops"
  values:
    layout: page
    page_display_sort_order: 100                       
-
  scope:
    path: ""
    type: "docker"
  values:
    layout: page
    page_display_sort_order: 100                           
-
  scope:
    path: ""
    type: "architecture"
  values:
    layout: page
    page_display_sort_order: 100    