FROM mcr.microsoft.com/dotnet/core/sdk:2.1 as Builder

RUN mkdir /app

RUN dotnet tool install --global Wyam.Tool

WORKDIR /app
COPY . .

RUN ~/.dotnet/tools/wyam build

FROM nginx:stable-alpine

RUN rm /usr/share/nginx/html/*
COPY --from=Builder /app/output /usr/share/nginx/html