# escape=`
FROM microsoft/dotnet-framework:4.7.2-sdk

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"] 

RUN New-Item -Path C:\app -ItemType Directory;

RUN dotnet tool install --global Wyam.Tool

WORKDIR C:\app
COPY . .

RUN C:\Users\ContainerAdministrator\.dotnet\tools\wyam build